version: "3.8"

volumes:
  cloud_data:

services:
  cloud-db:
    image: postgres:14.4-alpine
    healthcheck:
      test: [ "CMD-SHELL","pg_isready","-U","cloudadmin" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped
    container_name: cloud-db
    ports:
      - "5554:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: cloud_kg
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - cloud_data:/var/lib/postgresql/data